### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#1]
add a general contributing guide

**Comment by zpeters** [comment]
Pattern after https://github.com/IEEE-VIT/termiboard/blob/master/CONTRIBUTING.md

**Comment by orama254** [comment]
Greetings Zach,

Could you expand a bit more on the specifics of how the contributing.md should look like.

should it be a copy replica of the [IEEE-VIT](https://github.com/IEEE-VIT/termiboard/blob/master/CONTRIBUTING.md) example or are there extra details that you would like to be added?

kindly let me know

**Comment by zpeters** [comment]
Not an exact copy.  Just looking for an outline of the steps need to contribute to a github project.  Including forking the main repo, creating a branch and submitting a pull request. 

Thank you

**Comment by orama254** [comment]
OK noted...I'll work on something and send a pull request your way for review
