### ISSUE TITLE
cannot properly display some websites

### ISSUE THREAD

**Issue by dev-abir** [zpeters/stashbox#16]
[this](spring.io) website isn't rendered properly, after opening the `.html` file.

I think this tool is **just** for saving web pages as text?

**Comment by zpeters** [comment]
Ideally it will save as Text, Html and PDF.  I think html will be a challenge due to javascript. this may be somewhat resolved by the pdf.

Also we may want to grab additional resources (css, js, etc) that are referenced in the html file.  i need to put some thought into this

**Comment by dev-abir** [comment]
Most of the browsers today have a "save-as" option, how this program is different from that?
