### ISSUE TITLE
add code coverage badge to README.md

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#2]

**Comment by satriarrrrr** [comment]
@zpeters can you assign this to me?

**Comment by KrishKayc** [comment]
@zpeters  Have created PR for this. https://github.com/zpeters/stashbox/pull/69.

**Comment by KrishKayc** [comment]
@zpeters Can we close this bug as https://github.com/zpeters/stashbox/pull/69 is merged?

**Comment by zpeters** [comment]
Yes can be closed
