### ISSUE TITLE
Current file naming scheme does not work on Windows.

### ISSUE THREAD

**Issue by sharadbhat** [zpeters/stashbox#30]
```golang
t := time.Now()
dateTime := fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d",
	t.Year(), t.Month(), t.Day(),
	t.Hour(), t.Minute(), t.Second())

domainSubPath := path.Join(c.Archive, d, dateTime)
err = os.MkdirAll(domainSubPath, 0700)
if err != nil {
	return err
}
```

This code generates filename in the following format: `github.com/2020-10-02T20:28:51`. Colon is an invalid character for naming files in Windows.

**Comment by zpeters** [comment]
Care to create a pull request for a fix?

**Comment by zpeters** [comment]
closing and referring you to #7

**Comment by sharadbhat** [comment]
Sure @zpeters, for a quick fix, we can look at replacing colons with underscores.
Let me know what you think of it and I'll create a PR.
