### ISSUE TITLE
create pr template (re pr 31)

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#32]
See comments in #31 

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by sharadbhat** [comment]
I can pick this up @zpeters

**Comment by aesherman** [comment]
I'd like to take this (or we both can and just pick one to accept)

**Comment by sharadbhat** [comment]
Go ahead @aesherman

**Comment by zpeters** [comment]
Merged.  Thank you!
