### ISSUE TITLE
`AddUrl` needs a sanity check for URLs

### ISSUE THREAD

**Issue by Chopinsky** [zpeters/stashbox#36]
Currently, when adding an URL to crawl from the command line, we won't check if the URL input is valid. We will rely on the `http` client (which is used as the foundation of the crawler) to tell us if we have a valid URL string or not. 

This can be inconvenient when the user added a number of URLs already, but only one of them were entered incorrectly due to a typo, but now the crawling job would fail for the rest of the URLs. A common mistake is to omit the `http://` or `https://` protocol prefix of the URL strings. 

I think we can at least add some simple sanity checks and reject obvious illegal URL entries, and let the `http` package determine if it can handle the entry or not for the rest of them.

**Comment by cvhariharan** [comment]
Hi, I can pick this up if it is still open. :smile:
