### ISSUE TITLE
stashDb structure/layout

### ISSUE THREAD

**Issue by benprew** [zpeters/stashbox#40]
I found your project through Digital Ocean's Hacktober program, thanks for submitting your repo, there aren't a lot of golang repos listed (at least when I looked yesterday).

I was looking at your project and have been thinking about a couple of things:

1. Doing diffs between webpage versions

Downloading a web page as a pdf is nice, but makes it difficult to store just the changes between versions.  It also makes it difficult to identify what has changed between versions.  [ImageMagick can diff pdfs](https://stackoverflow.com/questions/5132749/diff-an-image-using-imagemagick), but only a single page at a time.

I'd propose using something like [monolith](https://github.com/Y2Z/monolith) to save the page as a single html page and then use diff to show differences.

2. Storing multiple versions of page

If you use the html representation of a page, you could then store the delta between versions, instead of storing the entire html file each time.

3. Export instead of storing multiple versions of the same webpage

Instead of having a .html, .txt and .pdf version of a page, have an export command that transforms the format on disk to the format requested. If you're storing a monolith .html file, you can call wkhtmltopdf on it to generate a pdf ondemand.

4. File layout

Instead of using the title of the page as the filename (which can change), you probably either to have a map of url -> page_id and store the file as <page_id>.html.  This insulates you from changes to the page title and means you don't have to represent the url structure as a file structure on disk.

If you wanted to be fancy, this could be a sqllite database stored in the stashDB directory, or it could be as simple as a JSON/YAML file in the stashDB directory.

5. Misc: Other commands

Ok, this isn't related to the structure or layout, but defining the structure/layout of the archive helps enable features like:

-list -- list all the pages I've saved and # of versions
-export -- export a webpage in html, pdf, text, markdown, etc...
-update -- update all webpages I've saved to the latest version, could also take a domain argument to limit to pages from a specific domain

Thanks and let me know what you think.

**Comment by benprew** [comment]
Also, the Wayback Archive has a tool for diffing rendered snapshots: 

https://web.archive.org/web/diff/20181006193011/20161204182951/http://archive.darpa.mil/shredderchallenge/

I wonder if they've open sourced that somewhere (it's still listed as in "beta")

**Comment by zpeters** [comment]
@benprew thank you for all of the suggestions.  I can tell you have put some thought into this and i really appreciate that.  its going to take me some time to really digest everything and think about it but i do see some real value in this.  I had not considered the idea of diffing over time instead of downloading a full copy each time.  I'm going to have to consider that.

The monolith command/strategy is interesting.  My main reason for dumping to PDF in the first place is really just wanting to be able to render something as close as possible to what was seen by the browser.  My impetus for all this is revisiting old bookmark links that have disappeared.  But then i got thinking that this could be useful as a "fact checker" - notifying me when content has *slightly* altered.

Thanks again.  If you feel strongly about any of these points please feel free to open an individual issue or a PR.  

Cheers!

**Comment by benprew** [comment]
Thanks @zpeters, I'll do some more thinking about some of my suggestions, and I agree that if you're just looking to archive old bookmarks, you're probably not doing regular updates of the pages, just to see if something has changed, although it would be nice to do diffs of the content in some cases.

I put together a script to do something similar, although it's not an "archive", it just converts an html page to markdown, using Mozilla's "reader mode" to render a simplified version of the page before converting it to markdown: https://github.com/benprew/clippy

It might also be interesting to integrate this archive into a browser add-on, it could behave like the bookmark function, but it would save a pdf instead of just a link.  In that setting, StashDb might function more like an API backend.

Sorry, now I'm kinda spitballing, but if I come up with some things, I'll open individual issues and put up some PRs.

Thanks!

**Comment by zpeters** [comment]
Thanks again for your thoughts on this.  I took some notes last night..  I'm going to close this actual issue out and open up new ones to keep organized.

Thanks!
