### ISSUE TITLE
Create something in the readme or somewhere else to highlight contributors

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#53]

**Comment by benprew** [comment]
In another repo of mine, I wrote a command to search through the git history and find build a list of authors, maybe something like that would work?  https://github.com/benprew/pony/blob/master/Rakefile#L34 

There's also the contributors page in github, could link to that in the readme? https://github.com/zpeters/stashbox/graphs/contributors

**Comment by zpeters** [comment]
i like the idea of a link to the contrib. page .  Thanks!
