### ISSUE TITLE
in crawler_test TestSave figure out how to run in github test environment

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#64]
I have _wkhtmltopdf_ installing as part of the test process, but there is the error below about a display.

Figure out either how to get this to run in github, or how to exclude just this one test in github

```
  crawler_test.go:37: 
        	Error Trace:	crawler_test.go:37
        	Error:      	Received unexpected error:
        	            	QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
        	            	qt.qpa.screen: QXcbConnection: Could not connect to display 
        	            	Could not connect to any X display.
        	Test:       	TestSave
```

**Comment by KrishKayc** [comment]
@zpeters we could abstract away generatePDF into a interface and test other lines of saveSites() with a fake interface in test alone.

**Comment by zpeters** [comment]
@KrishKayc I merged in the change to all it to run as is, but I am very interested in abstracting this (and other) parts of the code so we can have some quick unit tests and then a more thorough integration test.  Feel free to open an issue or or if you have some thoughts on this.  

Thank you and @benprew for all the help!

**Comment by KrishKayc** [comment]
@zpeters Yup, I think we need to abstract os.MkdirAll, ioutil.WriteFile and generatePDF into an interface (may be "Writer"). In this way, unit tests will be independent of the filesystem and run faster. Will create an issue
