### ISSUE TITLE
Error listing archives Error building archive

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#66]
If you add a domain and then another path from that domain it fails

### Steps to reproduce
```
./stashbox add -u https://thehelpfulhacker.net                                                   
Crawling https://thehelpfulhacker.net...
Saving https://thehelpfulhacker.net...

/stashbox list                                              
Archive listing...
1. thehelpfulhacker.net [1 image(s)]

./stashbox add -u https://thehelpfulhacker.net/posts/2020-10-13-golang-testify-table-tests/                                                 
Crawling https://thehelpfulhacker.net/posts/2020-10-13-golang-testify-table-tests/..
Saving https://thehelpfulhacker.net/posts/2020-10-13-golang-testify-table-tests/...

./stashbox list
Error listing archives Error building archive
```

**Comment by benprew** [comment]
Looks like this bug was introduced in #2ed0cf1665f14c24ae4e198ff0da8fc0a788ad5a .  Looking at the test that was added, was the intent to fail the build if a filename has an invalid timestamp in the file?

**Comment by erizkiatama** [comment]
Hello! I tried to reproduce this case and it turns out not only another path from the same domain that fails, but also different domain.
```
./stashbox add -u  https://digitalocean.com
Crawling https://digitalocean.com...
Saving https://digitalocean.com...

./stashbox list
Archive listing...
1. digitalocean.com [1 image(s)]

./stashbox add -u https://thehelpfulhacker.net                                                   
Crawling https://thehelpfulhacker.net...
Saving https://thehelpfulhacker.net...

./stashbox list
Error listing archives Error building archive
```

Could I try to work on this Issue? Thank you!

**Comment by benprew** [comment]
Go ahead @erizkiatama, I'm not working on this issue.

Thanks for helping!

**Comment by erizkiatama** [comment]
> Looks like this bug was introduced in [2ed0cf1](https://github.com/zpeters/stashbox/commit/2ed0cf1665f14c24ae4e198ff0da8fc0a788ad5a) . Looking at the test that was added, was the intent to fail the build if a filename has an invalid timestamp in the file?

This got me confused as well, is this failing only when filename has an invalid timestamp or when the URL page is invalid too?

Ah also when we add another path of same domain, would it got its own line in the list? For example steps above for `thehelpfulhacker.net`, would it be:
```
./stashbox list
Archive listing...
1. thehelpfulhacker.net [1 image(s)]
2. thehelpfulhacker.net/posts/2020-10-13-golang-testify-table-tests [1 image(s)]

OR

./stashbox list
Archive listing...
1. thehelpfulhacker.net [2 image(s)]
```

**Comment by erizkiatama** [comment]
> > Looks like this bug was introduced in [2ed0cf1](https://github.com/zpeters/stashbox/commit/2ed0cf1665f14c24ae4e198ff0da8fc0a788ad5a) . Looking at the test that was added, was the intent to fail the build if a filename has an invalid timestamp in the file?
> 
> This got me confused as well, is this failing only when filename has an invalid timestamp or when the URL page is invalid too?
> 
> Ah also when we add another path of same domain, would it got its own line in the list? For example steps above for `thehelpfulhacker.net`, would it be:
> 
> ```
> ./stashbox list
> Archive listing...
> 1. thehelpfulhacker.net [1 image(s)]
> 2. thehelpfulhacker.net/posts/2020-10-13-golang-testify-table-tests [1 image(s)]
> 
> OR
> 
> ./stashbox list
> Archive listing...
> 1. thehelpfulhacker.net [2 image(s)]
> ```

For now, I made an assumption that:

- Error will be given when filename has an invalid timestamp.
- When we add another path of same domain, it would got its own line in the list.

Please review the code and tell me if there is any problem. Happy Hacktober!
